### PR TITLE
Branch refactoring new

### LINKED ISSUE #60: Refactor Person model to Student model
## To be done nearer to deadline to prevent conflicts with team's commits
- Add attribute `float initial score`

### LINKED ISSUE #138: [PE-D][Tester D] Wrong product name in error message of duplicate person added
The product name should not be "address book"

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: Zhongli5712/ped#2

### LINKED ISSUE #147: [PE-D][Tester D] command in case-insensitive
Command different from specified in the UG in terms of case (like "LiST", "aDD", ...) still got accepted, since it is not specified in the UG it seems like a possible bug (intended behavior would be wrong format error showed)

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: Zhongli5712/ped#5

### PR DESCRIPTION
**Pull request by QQH0828**
# Changes

- Refactoring the whole project
  - Change `AddressBook` to `Mathutoring`
  - Change `Person` to  `Student`
- Remove some unused methods
- Change the command word to case-insensitive
   - e.g. `list` can be any type of `List`, `LIST`, `liST` ...
- Add a note in User Guide for `list`, `clear`, `switch` and `exit` command
   - Any information behind these command words will be ignored
- Update DG: 
  - Update corresponding diagrams
  - Except for the model part
- Solve `deletescore` will not reflect on the ui
- Disable entering future date for score
Disable future date

- Solve color change when selecting the score summary table
tableselected

- Add restriction to phone number: no more than 15 digits long
phonedigits
parentphone

- ScoreList sometimes does not show the correct order in the UI (Solved)
  - It shows the correct order on the chart and exports progress report
  - I have this issue after doing the conflicts. Maybe some part got an issue, I am still trying to solve it
  - But it will work fine when you start the application

# Unsloved
- Did not update the UML diagrams for the model part
  - When I was trying to edit it, the diagram was not enlarged automatically

# Before merging, please change to this branch, and run the application to see the behaviours
- Just to make sure anything works fine since I am not sure did I accidentally delete/change anything when I was solving the conflicts. 
- Any changes just let me know

# Issues
- resolves #60
- resolves #138 
- resolves #147

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/CheckCommand.java [hunk 1]
```diff
@@ -37,15 +37,15 @@ public CheckCommand(Index targetIndex) {
...
-            throw new CommandException(Messages.MESSAGE_INVALID_PERSON_DISPLAYED_INDEX);
+            throw new CommandException(Messages.MESSAGE_INVALID_STUDENT_DISPLAYED_INDEX);
         }
 
-        Person personToCheck = personList.get(targetIndex.getZeroBased());
-        model.checkPerson(personToCheck);
+        Student personToCheck = studentList.get(targetIndex.getZeroBased());
+        model.checkStudent(personToCheck);
 
         return new CommandResult(String.format(MESSAGE_CHECK_PERSON_SUCCESS, personToCheck));
```
Comment (toh-xinyi) [inline src/main/java/seedu/address/logic/commands/CheckCommand.java:50]:
```suggestion
        return new CommandResult(String.format(MESSAGE_CHECK_STUDENT_SUCCESS, personToCheck));
```

File: src/main/java/seedu/address/logic/commands/AddCommand.java [hunk 2]
```diff
@@ -36,28 +36,28 @@ public class AddCommand extends Command {
             + PREFIX_TAG + "friends "
             + PREFIX_TAG + "owesMoney";
 
-    public static final String MESSAGE_SUCCESS = "New person added: %1$s";
-    public static final String MESSAGE_DUPLICATE_PERSON = "This person already exists in the address book";
+    public static final String MESSAGE_SUCCESS = "New student added: %1$s";
+    public static final String MESSAGE_DUPLICATE_PERSON = "This student already exists in the mathutoring";
```
Comment (toh-xinyi) [inline src/main/java/seedu/address/logic/commands/AddCommand.java:40]:
```suggestion
    public static final String MESSAGE_DUPLICATE_STUDENT = "This student already exists in the mathutoring";
```

File: src/main/java/seedu/address/logic/commands/AddScoreCommand.java [hunk 3]
```diff
@@ -42,7 +42,7 @@ public class AddScoreCommand extends Command {
     private final Score toAdd;
```
Comment (toh-xinyi) [inline src/main/java/seedu/address/logic/commands/AddScoreCommand.java:42]: Line 38 above: change `MESSAGE_DUPLICATE_PERSON` to `MESSAGE_DUPLICATE_SCORE`

File: src/main/java/seedu/address/logic/commands/EditCommand.java [hunk 4]
```diff
@@ -20,24 +20,23 @@
...
+import seedu.address.model.student.Name;
+import seedu.address.model.student.Phone;
+import seedu.address.model.student.Student;
 import seedu.address.model.tag.Tag;
-import seedu.address.model.task.TaskList;
+
 
 /**
- * Edits the details of an existing person in the address book.
+ * Edits the details of an existing student in the math tutoring.
```
Comment (toh-xinyi) [inline src/main/java/seedu/address/logic/commands/EditCommand.java:32]:
```suggestion
 * Edits the details of an existing student in the mathutoring.
```

File: src/main/java/seedu/address/logic/commands/ExportProgressCommand.java [hunk 5]
```diff
@@ -47,29 +47,29 @@ public ExportProgressCommand(Index targetIndex, String filePath) {
     @Override
```
Comment (toh-xinyi) [inline src/main/java/seedu/address/logic/commands/ExportProgressCommand.java:47]: Line 39 above: refactor person to student

File: src/main/java/seedu/address/logic/commands/FilterCommand.java [hunk 6]
```diff
@@ -11,6 +11,7 @@
  * filter keywords.
```
Comment (toh-xinyi) [inline src/main/java/seedu/address/logic/commands/FilterCommand.java:11]: Line 10 above + Line 18: refactor person to student

File: src/main/java/seedu/address/logic/commands/FilterCommand.java [hunk 7]
```diff
@@ -11,6 +11,7 @@
...
  * Keyword matching is case insensitive and need to be exact match.
  */
+
```
Comment (toh-xinyi) [inline src/main/java/seedu/address/logic/commands/FilterCommand.java:14]: Remove this space between javadoc comment and the class

File: src/main/java/seedu/address/logic/parser/AddCommandParser.java [hunk 8]
```diff
@@ -47,9 +48,9 @@ public AddCommand parse(String args) throws ParseException {
         Phone parentPhone = ParserUtil.parsePhone(argMultimap.getValue(PREFIX_PARENT_PHONE).get());
         Set<Tag> tagList = ParserUtil.parseTags(argMultimap.getAllValues(PREFIX_TAG));
 
-        Person person = new Person(name, phone, email, address, parentPhone, tagList);
+        Student student = new seedu.address.model.student.Student(name, phone, email, address, parentPhone, tagList);
```
Comment (toh-xinyi) [inline src/main/java/seedu/address/logic/parser/AddCommandParser.java:51]:
```suggestion
        Student student = new Student(name, phone, email, address, parentPhone, tagList);
```

**Review by toh-xinyi — COMMENTED** [review]
Other than some minor edits, LGTM

File: src/main/java/seedu/address/logic/commands/ClearCommand.java [hunk 9]
```diff
@@ -2,23 +2,24 @@
...
+
 /**
- * Clears the address book.
+ * Clears the math tutoring.
  */
 public class ClearCommand extends Command {
 
     public static final String COMMAND_WORD = "clear";
-    public static final String MESSAGE_SUCCESS = "Address book has been cleared!";
+    public static final String MESSAGE_SUCCESS = "Mathutoring has been cleared!";
```
[the remark this answers is not in the document]
Comment (QQH0828) [reply src/main/java/seedu/address/logic/commands/ClearCommand.java:15]: Thanks for the suggestions!

**Comment by QQH0828** [comment]
> Other than some minor edits, LGTM

Thank you for checking so carefully！

File: docs/UserGuide.md [hunk 10]
```diff
@@ -74,6 +77,10 @@ Prompts the help page link.
 
 Format: `help`
 
+Note:
+
+* Any information behind `help` will be ignored.
```
Comment (toh-xinyi) [inline docs/UserGuide.md:82]: This is mentioned in line 64 le, won't need to reiterate here

File: src/test/java/seedu/address/logic/commands/DeleteCommandTest.java [hunk 11]
```diff
@@ -94,16 +94,16 @@ public void equals() {
...
 
-        // different person -> returns false
+        // different student -> returns false
         assertFalse(deleteFirstCommand.equals(deleteSecondCommand));
     }
 
     /**
      * Updates {@code model}'s filtered list to show no one.
      */
     private void showNoPerson(Model model) {
```
Comment (toh-xinyi) [inline src/test/java/seedu/address/logic/commands/DeleteCommandTest.java:104]:
```suggestion
    private void showNoStudent(Model model) {
```
A few of the other tests have some parts that are not refactored yet, but I think can just leave it ba.

**Review by toh-xinyi — CHANGES_REQUESTED** [review]
LGTM, just some small changes to be made

**Comment by QQH0828** [comment]
Thank you for checking so carefully！I have changed them all.

File: docs/UserGuide.md [hunk 12]
```diff
@@ -94,6 +97,10 @@ Prompts the help page link.
...
+
```
[the remark this answers is not in the document]
Comment (QQH0828) [reply docs/UserGuide.md]: So sorry, I missed this part.

File: src/test/java/seedu/address/model/student/UniqueStudentListTest.java [hunk 13]
```diff
@@ -0,0 +1,170 @@
...
+import seedu.address.model.student.exceptions.DuplicateStudentException;
+import seedu.address.model.student.exceptions.StudentNotFoundException;
+import seedu.address.testutil.StudentBuilder;
+
+public class UniqueStudentListTest {
+
+    private final UniqueStudentList uniqueStudentList = new UniqueStudentList();
+
+    @Test
+    public void contains_nullPerson_throwsNullPointerException() {
```
[the remark this answers is not in the document]
Comment (toh-xinyi) [reply src/test/java/seedu/address/model/student/UniqueStudentListTest.java]: Thank you! 😁

File: src/main/java/seedu/address/logic/commands/AddScoreCommand.java [hunk 14]
```diff
@@ -35,14 +35,14 @@ public class AddScoreCommand extends Command {
             + PREFIX_SCORE_DATE + "2012-08-09 ";
 
     public static final String MESSAGE_SUCCESS = "Added score to Student %1$s: %2$s";
-    public static final String MESSAGE_DUPLICATE_PERSON = "This score already exists in this student's score list";
+    public static final String MESSAGE_DUPLICATE_STUDENT = "This score already exists in this student's score list";
```
[the remark this answers is not in the document]
Comment (QQH0828) [reply src/main/java/seedu/address/logic/commands/AddScoreCommand.java]: I actually changed this, but somehow when I commit, the source tree converts back to the previous version. Anyway, I changed it again. Thanks a lot!

[the remark this answers is not in the document]
Comment (toh-xinyi) [reply src/main/java/seedu/address/logic/commands/AddScoreCommand.java]: Ohh I see, okay! Thank you!

**Review by toh-xinyi — APPROVED** [review]
LGTM, thanks for helping to refactor! 😁

File: src/main/java/seedu/address/logic/commands/AddCommand.java [hunk 15]
```diff
@@ -36,28 +36,28 @@ public class AddCommand extends Command {
             + PREFIX_TAG + "friends "
             + PREFIX_TAG + "owesMoney";
```
Comment (toh-xinyi) [inline src/main/java/seedu/address/logic/commands/AddCommand.java:37]:
```suggestion
            + PREFIX_TAG + "primary"
            + PREFIX_TAG + "primary6";
```

**Review by toh-xinyi — COMMENTED** [review]
Forgot about this, could you help me change this? Thank you!

**Review by gwynethguo — CHANGES_REQUESTED** [review]
LGTM! Thanks for refactoring :D Just one suggestion :)

File: src/main/java/seedu/address/logic/commands/AddCommand.java [hunk 16]
```diff
@@ -36,28 +36,28 @@ public class AddCommand extends Command {
             + PREFIX_TAG + "friends "
```
Comment (CarrieLi1015) [inline src/main/java/seedu/address/logic/commands/AddCommand.java:36]: Can consider to have a "female"/"male" tag. As the avatar will change based on the gender.

File: src/main/java/seedu/address/logic/commands/AddScoreCommand.java [hunk 17]
```diff
@@ -35,14 +35,14 @@ public class AddScoreCommand extends Command {
             + PREFIX_SCORE_DATE + "2012-08-09 ";
 
     public static final String MESSAGE_SUCCESS = "Added score to Student %1$s: %2$s";
-    public static final String MESSAGE_DUPLICATE_PERSON = "This score already exists in this student's score list";
+    public static final String MESSAGE_DUPLICATE_SCORE = "This score already exists in this student's score list";
```
Comment (CarrieLi1015) [inline src/main/java/seedu/address/logic/commands/AddScoreCommand.java:38]: Maybe can consider to have a more specific error message since quite a number of the tester are confused about this part. Change to "Every score must have different date".

File: docs/tutorials/TracingCode.md [hunk 18]
```diff
@@ -189,22 +189,22 @@ Recall from the User Guide that the `edit` command has the format: `edit INDEX [
...
-   * it uses the `setPerson()` method (defined in the interface `Model` and implemented in `ModelManager` as per the usual pattern) to update the person data.
-   * it uses the `updateFilteredPersonList` method to ask the `Model` to populate the 'filtered list' with _all_ persons.<br>
-     FYI, The 'filtered list' is the list of persons resulting from the most recent operation that will be shown to the user immediately after. For the `edit` command, we populate it with all the persons so that the user can see the edited person along with all other persons. If this was a `find` command, we would be setting that list to contain the search results instead.<br>
-     To provide some context, given below is the class diagram of the `Model` component. See if you can figure out where the 'filtered list' of persons is being tracked.
+   * it uses the `setPerson()` method (defined in the interface `Model` and implemented in `ModelManager` as per the usual pattern) to update the student data.
+   * it uses the `updateFilteredPersonList` method to ask the `Model` to populate the 'filtered list' with _all_ students.<br>
```
Comment (CarrieLi1015) [inline docs/tutorials/TracingCode.md:205]: Should here be `updateFilterStudentList` instead?

**Review by CarrieLi1015 — COMMENTED** [review]
LGMT, just a few suggestion.

File: docs/tutorials/TracingCode.md (hunk 18 above)
Comment (QQH0828) [reply docs/tutorials/TracingCode.md:205]: Thanks for listing them out. But do we need to consider this doc also, since it is not UG and DG. But I still change the method name inside the doc.

File: src/main/java/seedu/address/logic/commands/AddScoreCommand.java (hunk 17 above)
Comment (QQH0828) [reply src/main/java/seedu/address/logic/commands/AddScoreCommand.java:38]: Sure, thanks

File: src/main/java/seedu/address/logic/commands/AddCommand.java (hunk 15 above)
Comment (QQH0828) [reply src/main/java/seedu/address/logic/commands/AddCommand.java:37]: Sure

**Review by gwynethguo — APPROVED** [review]
LGTM
